apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: {{ .Values.name }}-configmap
data:
  config.yaml: |
    postgres:
      user: {{ .Values.postgres.user }}
      host: {{ .Values.postgres.host }}
      port: {{ .Values.postgres.port }}
      dbname: {{ .Values.postgres.dbname }}

    server:
      port: {{ .Values.eventProvider.port }}
    healthz:
      port: {{ .Values.healthz.port }}
    virtualGarden:
      name: {{ .Values.eventProvider.virtualGarden.name }}
      dnsName: {{ .Values.eventProvider.virtualGarden.dnsName }}