apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port":3200}]'
    networking.resources.gardener.cloud/from-all-garden-scrape-targets-allowed-ports: '[{"port":8080,"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: provider
  {{- if .Values.eventProvider.tlsServer }}
    port: 443
  {{- else }}
    port: 3200
  {{- end }}
    targetPort: 3200
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  {{- if .Values.eventProvider.useIngress }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}

