apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - name: provider
  {{- if .Values.eventProvider.tlsServer }}
    port: 443
  {{- else }}
    port: 80
  {{- end }}
    targetPort: 3200
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  {{- if .Values.eventProvider.useIngress }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}

