apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  postgres_password: {{ .Values.postgres.password | b64enc }}
  gardener_access_token: {{ .Values.gardener.accessToken | b64enc }}