apiVersion: v1
kind: Secret
metadata:
  name: provider-secrets
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc }}
  garden-kubeconfig: {{ .Values.gardener.accessToken | b64enc }}
