name: falco-event-provider

eventProvider:
  useIngress: true
  ingressDomain:
  ingressClassName: nginx-ingress-gardener
  image: 
    repository: europe-docker.pkg.dev/gardener-project/releases/gardener/falco-event-provider
    tag: 0.0.1
  port: 3200
  tlsServer: false
  replicas: 2
  virtualGarden:
    name: "" # sap-landscape-dev
    dnsName: virtual-garden-kube-apiserver
### The gardenDNSProvider section is needed if the garden-runtime cluster uses the garden cert-controller-manager
### Values are from the `Garden` resource at `.spec.dns.providers[0]`
# gardenDNSProvider:
#   secretRef:
#     namespace: garden
#     name: garden-gardener-dns
#   type: aws-route53

postgres:
  user: gardener
  host: falco-event-db.falco-event-storage.svc.cluster.local
  port: 5432
  dbname: falco
  password: ""
  pageSize: 1000

healthz:
  port: 8000

gardener:
  kubeconfig: "Cg=="
  accessToken: ""
