name: falco-event-provider

eventProvider:
  useIngress: true
  ingressDomain:
  ingressClassName: nginx-ingress-gardener
  image: 
    repository: europe-docker.pkg.dev/gardener-project/releases/gardener/falco-event-provider
    tag: 0.0.1
  port: 3200
  tlsServer: false
  replicas: 2
  virtualGarden:
    name: "" # sap-landscape-dev
    dnsName: virtual-garden-kube-apiserver

postgres:
  user: gardener
  host: falco-event-db.falco-event-storage.svc.cluster.local
  port: 5432
  dbname: falco
  password: ""

healthz:
  port: 8000

gardener:
  kubeconfig: "Cg=="
  accessToken: ""